/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BMapViewer: typeof import('./src/components/BMapViewer.vue')['default']
    CardView: typeof import('./src/components/CardView.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElPageHeader: typeof import('element-plus/es')['ElPageHeader']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
